# Use the built-in input function to get first name, last name, country and age 
# from a user and store the value to their corresponding variable names
first_name = input('Enter First name: ')
middle_name = input('Enter middle name: ')
last_name = input('Enter last name: ')
country = input('Enter Country: ')
city = input('Enter your City: ')
age = int(input('Enter your age: '))
year = int(input('Enter year: '))
print(type(first_name))
print(type(middle_name))
print(type(last_name))
print(type(country))
print(type(city))
print(type(age))
print(type(year))
print('First Name: ',first_name)
print('Middle Name: ',middle_name)
print('Last Name: ',last_name)
print('Country: ',country)
print('City: ',city)
print('Age: ',age)
print('Year: ',year)